### ISSUE TITLE
StreamError/unsupported-stanza-type

### ISSUE THREAD

**Issue by ghost** [thisismedium/python-xmpp-server#2]
After switching to SSLv2(see previous bug), i could connect to the server with kopete. Pidgin didn't connect, but instead returned something like: "SASL-error: generic failure: Server doesn't support "no layer". Maybe this has to do with the type of ssl, i'm not sure. With kopete, when i try to message another user, it returns the following traceback:

root@osnwork:~/python-xmpp-server/examples# python chat-server.py
Caught StreamError while dispatching '{jabber:client}iq/{jabber:iq:private}query'.
Traceback (most recent call last):
File "/usr/local/lib/python2.6/dist-packages/python_xmpp_server-0.1-py2.6.egg/xmpp/core.py", line 299, in info_query
self.state.trigger_stanza(name, elem)
File "/usr/local/lib/python2.6/dist-packages/python_xmpp_server-0.1-py2.6.egg/xmpp/state.py", line 118, in trigger_stanza
'Unrecognized stanza %r.' % name
StreamError: unsupported-stanza-type: Unrecognized stanza '{jabber:client}iq/{jabber:iq:private}query'.
Caught StreamError while dispatching '{jabber:client}iq/{jabber:iq:private}query'.
Traceback (most recent call last):
File "/usr/local/lib/python2.6/dist-packages/python_xmpp_server-0.1-py2.6.egg/xmpp/core.py", line 299, in info_query
self.state.trigger_stanza(name, elem)
File "/usr/local/lib/python2.6/dist-packages/python_xmpp_server-0.1-py2.6.egg/xmpp/state.py", line 118, in trigger_stanza
'Unrecognized stanza %r.' % name
StreamError: unsupported-stanza-type: Unrecognized stanza '{jabber:client}iq/{jabber:iq:private}query'.

**Comment by thisismedium** [comment]
These "Unrecognized stanza" errors are non-fatal notifications that there's not a handler installed for that particular kind of stanza.  The logging level for these notifications has been downgraded from "exception" to "debug".

**Comment by ghost** [comment]
Thank you for publishing this software. I'll try to read up, and hope i can contribute something to it, once i understand it :-)
